# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=64)),
                ('api_url', models.CharField(max_length=64)),
                ('request_example', models.CharField(max_length=1024)),
                ('response_success_example', models.CharField(max_length=1024)),
                ('response_fail_example', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ApiClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=32)),
                ('field_escribe', models.CharField(max_length=1024)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Dict')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=64)),
                ('signature_rule', models.CharField(max_length=1024)),
                ('test_root_url', models.CharField(max_length=64)),
                ('formal_root_url', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_describe', models.CharField(max_length=64)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Platform')),
            ],
        ),
        migrations.AddField(
            model_name='apiclass',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Platform'),
        ),
        migrations.AddField(
            model_name='api',
            name='api_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.ApiClass'),
        ),
        migrations.AddField(
            model_name='api',
            name='request_field',
            field=models.ManyToManyField(related_name='request_field', to='doc.Field'),
        ),
        migrations.AddField(
            model_name='api',
            name='request_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Dict'),
        ),
        migrations.AddField(
            model_name='api',
            name='response_field',
            field=models.ManyToManyField(related_name='response_field', to='doc.Field'),
        ),
    ]
