# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-28 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_key', models.CharField(max_length=10)),
                ('dict_value', models.IntegerField()),
                ('dic_type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='field_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='field',
            name='is_must',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statuscode',
            name='status_code_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='request_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.DataDict'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.DataDict'),
        ),
        migrations.DeleteModel(
            name='Dict',
        ),
    ]
