# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-29 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_auto_20160429_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='api_describe',
            field=models.TextField(max_length=64, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='api',
            name='api_status',
            field=models.IntegerField(choices=[(1, '开通'), (2, '未开通')], default=2, verbose_name='开通状态'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.ApiClass', verbose_name='api类别'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_url',
            field=models.CharField(max_length=64, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='api',
            name='request_example',
            field=models.TextField(max_length=1024, verbose_name='请求示例'),
        ),
        migrations.AlterField(
            model_name='api',
            name='request_method',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'DELETE'), (4, 'PUT')], verbose_name='请求协议'),
        ),
        migrations.AlterField(
            model_name='api',
            name='response_fail_example',
            field=models.TextField(max_length=1024, verbose_name='请求失败示例'),
        ),
        migrations.AlterField(
            model_name='api',
            name='response_success_example',
            field=models.TextField(max_length=1024, verbose_name='请求成功示例'),
        ),
        migrations.AlterField(
            model_name='apiclass',
            name='clas_name',
            field=models.CharField(max_length=64, verbose_name='api类别'),
        ),
        migrations.AlterField(
            model_name='apiclass',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_describe',
            field=models.TextField(max_length=1024, null=True, verbose_name='阐述描述'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_length',
            field=models.IntegerField(blank=True, verbose_name='长度'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(max_length=32, verbose_name='参数名称'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.IntegerField(choices=[(1, 'String'), (2, 'int'), (3, 'long'), (4, 'double')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_must',
            field=models.BooleanField(default=False, verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='formal_root_url',
            field=models.CharField(max_length=64, verbose_name='正式根地址'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(max_length=64, verbose_name='平台名称'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='signature_rule',
            field=models.TextField(max_length=1024, verbose_name='签名规则'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='test_root_url',
            field=models.CharField(max_length=64, verbose_name='测试根地址'),
        ),
        migrations.AlterField(
            model_name='requestfield',
            name='api_requset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_requset', to='doc.Api', verbose_name='api'),
        ),
        migrations.AlterField(
            model_name='responsefield',
            name='api_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_response', to='doc.Api', verbose_name='api'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.Platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='status_code_value',
            field=models.IntegerField(verbose_name='状态码'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='status_describe',
            field=models.TextField(max_length=1024, verbose_name='状态码描述'),
        ),
    ]
