# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-29 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_auto_20160429_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='parent_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='doc.Field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.IntegerField(choices=[(1, 'String'), (2, 'int'), (3, 'long'), (4, 'double'), (5, '对象')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='requestfield',
            name='api_requset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_requset_field', to='doc.Api', verbose_name='api'),
        ),
        migrations.AlterField(
            model_name='responsefield',
            name='api_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_response_field', to='doc.Api', verbose_name='api'),
        ),
    ]
