# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_auto_20160429_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to='doc.ApiClass', verbose_name='api类别'),
        ),
        migrations.AlterField(
            model_name='api',
            name='request_method',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'DELETE'), (4, 'PUT')], verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apiclass',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_class', to='doc.Platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_describe',
            field=models.TextField(max_length=1024, null=True, verbose_name='参数描述'),
        ),
        migrations.AlterField(
            model_name='field',
            name='parent_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='doc.Field', verbose_name='父参数'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_code', to='doc.Platform', verbose_name='平台'),
        ),
    ]
